### PR TITLE
Add flash message to users and entries actions

### PR DESCRIPTION
**Pull request by henriquepjv**
[Issue_11](https://github.com/teresinahc/carambolo/issues/11)

### Why
- We were not returning standardized messages to the user

### How
- Add flash message block to application layout to render all flash message from controllers actions

### CODE REVIEW

**Comment by marclerodrigues** [comment]
Hey, thanks for submitting this PR. Could you please add specs for the changes you made in the controllers?

**Comment by henriquepjv** [comment]
> Hey, thanks for submitting this PR. Could you please add specs for the changes you made in the controllers?

@marclerodrigues I just added the controllers tests :v:

**Comment by henriquepjv** [comment]
@marclerodrigues there is still something to fix?

**Comment by marclerodrigues** [comment]
LGTM, Thanks for your contribution @henriquepjv!

**Pull request merged**
